-- AlterTable
ALTER TABLE "cart_items" ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "catalog_products" ALTER COLUMN "mrp" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "gstPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "shippingCharges" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "commissionGstPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "commissionPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "fixedFee" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "fixedFeeGstPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "shippingGstPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "finalShippingPrice" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "categories" ALTER COLUMN "commissionGstPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "commissionPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "fixedFee" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "order_items" ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "totalPrice" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "orders" ALTER COLUMN "totalAmount" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "payments" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "seller_offers" ADD COLUMN     "finalCustomerPayable" DECIMAL(10,2),
ALTER COLUMN "mrp" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "gstPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "shippingCharges" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "finalShippingPrice" SET DATA TYPE DECIMAL(10,2);

-- AlterTable
ALTER TABLE "sub_categories" ALTER COLUMN "commissionGstPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "commissionPercent" SET DATA TYPE DECIMAL(10,2),
ALTER COLUMN "fixedFee" SET DATA TYPE DECIMAL(10,2);

