import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import axios, { AxiosError } from 'axios';
import * as crypto from 'crypto';
import { assertPublicHostname, normalizeStoreUrl } from '../store-url.util';
import { ExternalProductPage } from './external-product.types';

/** Only the fields of Woo's product payload this integration reads. */
interface WooRawProduct {
  id: number;
  name?: string;
  sku?: string;
  type?: string;
  stock_quantity?: number | null;
}

interface WooRawVariation {
  id: number;
  name?: string;
  sku?: string;
  stock_quantity?: number | null;
}

/**
 * WooCommerce authentication uses the store's own REST API key endpoint
 * (`/wc-auth/v1/authorize`), not OAuth. Yukizi sends the seller to their own
 * WordPress admin, they approve, and WooCommerce POSTs a freshly generated
 * consumer key/secret pair to our callback.
 *
 * The important consequence: credentials are per-store and generated by the
 * store. There is no global WooCommerce app secret in our environment.
 */

export interface WooCommerceCredentials {
  consumerKey: string;
  consumerSecret: string;
  keyPermissions: string;
  storeUrl: string;
}

export interface WooStoreCheck {
  reachable: boolean;
  isWooCommerce: boolean;
  /** Seller-facing sentence explaining exactly what failed. */
  message?: string;
}

@Injectable()
export class WooCommerceProvider {
  private readonly logger = new Logger(WooCommerceProvider.name);

  /**
   * WooCommerce is always available: it needs no platform-level app
   * registration, unlike Shopify and Amazon.
   */
  isConfigured(): boolean {
    return true;
  }

  /**
   * Pre-flight check before sending the seller away to authorise. Catching a
   * bad URL here means they see a useful message on the Yukizi modal instead
   * of a WordPress 404 after a redirect.
   *
   * Every branch maps to one of the failure modes sellers actually hit.
   */
  async checkStore(storeUrl: string): Promise<WooStoreCheck> {
    const normalized = normalizeStoreUrl(storeUrl);
    const { hostname } = new URL(normalized);

    // Re-resolve immediately before the request: a public-looking hostname
    // whose DNS points inside our network must not be fetched.
    await assertPublicHostname(hostname);

    try {
      // The REST index advertises WooCommerce's namespace when the plugin is
      // active and the API is reachable.
      const { data } = await axios.get<{ namespaces?: string[] }>(
        `${normalized}/wp-json/`,
        {
          timeout: 10_000,
          maxRedirects: 3,
          // Any 2xx/4xx is informative; only transport errors throw.
          validateStatus: (status) => status < 500,
          headers: { 'User-Agent': 'Yukizi-Integrations/1.0' },
        },
      );

      const namespaces = Array.isArray(data?.namespaces) ? data.namespaces : [];
      if (namespaces.some((ns) => String(ns).startsWith('wc/'))) {
        return { reachable: true, isWooCommerce: true };
      }

      if (namespaces.length > 0) {
        return {
          reachable: true,
          isWooCommerce: false,
          message:
            'This looks like a WordPress site, but the WooCommerce REST API is not enabled. Check that WooCommerce is active on the store.',
        };
      }

      return {
        reachable: true,
        isWooCommerce: false,
        message:
          "We reached this site but couldn't find the WordPress REST API. If WordPress permalinks are set to 'Plain', change them to 'Post name' and try again.",
      };
    } catch (error) {
      return {
        reachable: false,
        isWooCommerce: false,
        message: this.describeTransportError(error),
      };
    }
  }

  /**
   * Turns a transport failure into something a seller can act on. These are
   * the real-world WooCommerce connection problems: security plugins blocking
   * non-browser agents, expired certificates, firewalled hosts.
   */
  private describeTransportError(error: unknown): string {
    const axiosError = error as AxiosError;
    const code = axiosError?.code;
    const status = axiosError?.response?.status;

    if (code === 'ECONNABORTED' || code === 'ETIMEDOUT') {
      return 'The store took too long to respond. It may be slow or temporarily offline — try again in a few minutes.';
    }
    if (code === 'ENOTFOUND' || code === 'EAI_AGAIN') {
      return "We couldn't find that store domain. Check the store URL and try again.";
    }
    if (code === 'ECONNREFUSED' || code === 'ECONNRESET') {
      return "The store refused the connection. A firewall or security plugin may be blocking Yukizi.";
    }
    if (
      code === 'CERT_HAS_EXPIRED' ||
      code === 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' ||
      code === 'DEPTH_ZERO_SELF_SIGNED_CERT' ||
      code === 'ERR_TLS_CERT_ALTNAME_INVALID'
    ) {
      return "The store's SSL certificate could not be verified. Fix the HTTPS certificate on the store and try again.";
    }
    if (status === 403) {
      return 'The store blocked our request (HTTP 403). A WordPress security plugin such as Wordfence may need to allow Yukizi.';
    }
    if (status === 401) {
      return 'The store requires authentication before the REST API can be reached.';
    }
    return "We couldn't connect to this WooCommerce store. Check the store URL and try again.";
  }

  /**
   * Builds the WooCommerce authorisation URL.
   *
   * `user_id` is our own opaque state token: WooCommerce echoes it back on the
   * callback, which is how we tie the generated credentials to the seller who
   * started the flow. `return_url` is where the browser lands; `callback_url`
   * is the server endpoint WooCommerce POSTs the credentials to and must be
   * HTTPS or WooCommerce refuses the request outright.
   */
  buildAuthorizationUrl(params: {
    storeUrl: string;
    appName: string;
    state: string;
    returnUrl: string;
    callbackUrl: string;
  }): string {
    const normalized = normalizeStoreUrl(params.storeUrl);

    if (!params.callbackUrl.startsWith('https://')) {
      // Worth failing loudly in config rather than confusing the seller: Woo
      // silently rejects non-HTTPS callbacks.
      this.logger.error(
        'WooCommerce callback URL must be https:// — WooCommerce will reject the authorisation request.',
      );
    }

    const query = new URLSearchParams({
      app_name: params.appName,
      // read_write is the narrowest permission that still allows the inventory
      // updates this feature performs. Woo has no finer-grained scope.
      scope: 'read_write',
      user_id: params.state,
      return_url: params.returnUrl,
      callback_url: params.callbackUrl,
    });

    return `${normalized}/wc-auth/v1/authorize?${query.toString()}`;
  }

  /**
   * Confirms the delivered credentials actually work before we mark the
   * connection healthy. Uses HTTPS basic auth, which is WooCommerce's
   * documented scheme for TLS endpoints.
   */
  async verifyCredentials(
    storeUrl: string,
    consumerKey: string,
    consumerSecret: string,
  ): Promise<boolean> {
    const normalized = normalizeStoreUrl(storeUrl);
    await assertPublicHostname(new URL(normalized).hostname);

    try {
      const response = await axios.get(
        `${normalized}/wp-json/wc/v3/system_status`,
        {
          auth: { username: consumerKey, password: consumerSecret },
          timeout: 15_000,
          validateStatus: (status) => status < 500,
          headers: { 'User-Agent': 'Yukizi-Integrations/1.0' },
        },
      );

      if (response.status === 401 || response.status === 403) return false;
      if (response.status >= 400) {
        // Some hardened stores hide system_status; products is a safer probe.
        const fallback = await axios.get(
          `${normalized}/wp-json/wc/v3/products`,
          {
            auth: { username: consumerKey, password: consumerSecret },
            params: { per_page: 1 },
            timeout: 15_000,
            validateStatus: (status) => status < 500,
            headers: { 'User-Agent': 'Yukizi-Integrations/1.0' },
          },
        );
        return fallback.status < 400;
      }
      return true;
    } catch (error) {
      this.logger.warn(
        `WooCommerce credential check failed: ${(error as AxiosError)?.code ?? 'unknown'}`,
      );
      throw new BadRequestException(this.describeTransportError(error));
    }
  }

  /**
   * WooCommerce signs webhook payloads with an HMAC-SHA256 of the raw body,
   * base64 encoded, using the secret chosen when the webhook was created.
   */
  verifyWebhookSignature(
    rawBody: Buffer | undefined,
    signature: string | undefined,
    secret: string,
  ): boolean {
    if (!rawBody?.length || !signature || !secret) return false;
    const digest = crypto
      .createHmac('sha256', secret)
      .update(rawBody)
      .digest('base64');
    const a = Buffer.from(digest);
    const b = Buffer.from(signature);
    if (a.length !== b.length) return false;
    return crypto.timingSafeEqual(a, b);
  }

  /**
   * One page of products.
   *
   * WooCommerce uses ordinary page numbers, and reports the total page count in
   * the `x-wp-totalpages` header — which is how we know when to stop rather
   * than guessing from a short page.
   *
   * Variable products carry no SKU or stock of their own; the variations do.
   * So each variable product costs one extra request, which is why this is
   * paged rather than fetched all at once.
   */
  async fetchProductsPage(
    storeUrl: string,
    credentials: { consumerKey: string; consumerSecret: string },
    page = 1,
    perPage = 50,
  ): Promise<ExternalProductPage> {
    const normalized = normalizeStoreUrl(storeUrl);
    await assertPublicHostname(new URL(normalized).hostname);

    const auth = {
      username: credentials.consumerKey,
      password: credentials.consumerSecret,
    };

    const response = await axios.get<WooRawProduct[]>(
      `${normalized}/wp-json/wc/v3/products`,
      {
        auth,
        params: { per_page: Math.min(100, perPage), page, status: 'any' },
        timeout: 30_000,
        headers: { 'User-Agent': 'Yukizi-Integrations/1.0' },
      },
    );

    const products: ExternalProductPage['products'] = [];

    for (const product of response.data ?? []) {
      if (product.type === 'variable') {
        const variations = await this.fetchVariations(
          normalized,
          auth,
          product.id,
        );
        for (const variation of variations) {
          products.push({
            externalProductId: String(product.id),
            externalVariantId: String(variation.id),
            sku: variation.sku?.trim() || null,
            title: `${product.name ?? 'Product'}${
              variation.name ? ` — ${variation.name}` : ''
            }`,
            quantity:
              typeof variation.stock_quantity === 'number'
                ? variation.stock_quantity
                : null,
            fulfillmentChannel: 'MERCHANT' as const,
          });
        }
        continue;
      }

      products.push({
        externalProductId: String(product.id),
        externalVariantId: null,
        sku: product.sku?.trim() || null,
        title: product.name ?? null,
        quantity:
          typeof product.stock_quantity === 'number'
            ? product.stock_quantity
            : null,
        fulfillmentChannel: 'MERCHANT' as const,
      });
    }

    const totalPages = Number(response.headers?.['x-wp-totalpages'] ?? 1);
    return {
      products,
      nextCursor:
        Number.isFinite(totalPages) && page < totalPages ? String(page + 1) : null,
    };
  }

  /**
   * Writes an absolute stock quantity.
   *
   * A variation has its own endpoint; a simple product is updated directly.
   * `manage_stock: true` is sent alongside because a store that is not
   * managing stock for that product would otherwise accept the quantity and
   * silently ignore it.
   */
  async updateStockQuantity(
    storeUrl: string,
    credentials: { consumerKey: string; consumerSecret: string },
    productId: string,
    variationId: string | null,
    quantity: number,
  ): Promise<void> {
    const normalized = normalizeStoreUrl(storeUrl);
    await assertPublicHostname(new URL(normalized).hostname);

    const path = variationId
      ? `${normalized}/wp-json/wc/v3/products/${productId}/variations/${variationId}`
      : `${normalized}/wp-json/wc/v3/products/${productId}`;

    await axios.put(
      path,
      { manage_stock: true, stock_quantity: quantity },
      {
        auth: {
          username: credentials.consumerKey,
          password: credentials.consumerSecret,
        },
        timeout: 20_000,
        headers: { 'User-Agent': 'Yukizi-Integrations/1.0' },
      },
    );
  }

  /** Variations of one variable product. Capped: 100 is Woo's own maximum. */
  private async fetchVariations(
    normalizedStoreUrl: string,
    auth: { username: string; password: string },
    productId: number,
  ): Promise<WooRawVariation[]> {
    try {
      const { data } = await axios.get<WooRawVariation[]>(
        `${normalizedStoreUrl}/wp-json/wc/v3/products/${productId}/variations`,
        {
          auth,
          params: { per_page: 100 },
          timeout: 30_000,
          headers: { 'User-Agent': 'Yukizi-Integrations/1.0' },
        },
      );
      return data ?? [];
    } catch {
      // One unreadable product must not abort the whole import.
      this.logger.warn(`Could not read variations for product ${productId}`);
      return [];
    }
  }

  /**
   * Creates a webhook on the store. `secret` is generated by us so we can
   * verify deliveries; it is stored encrypted alongside the subscription.
   */
  async registerWebhook(
    storeUrl: string,
    credentials: WooCommerceCredentials,
    topic: string,
    deliveryUrl: string,
    secret: string,
  ): Promise<string | null> {
    const normalized = normalizeStoreUrl(storeUrl);
    try {
      const { data } = await axios.post<{ id: number }>(
        `${normalized}/wp-json/wc/v3/webhooks`,
        {
          name: `Yukizi ${topic}`,
          topic,
          delivery_url: deliveryUrl,
          secret,
          status: 'active',
        },
        {
          auth: {
            username: credentials.consumerKey,
            password: credentials.consumerSecret,
          },
          timeout: 15_000,
        },
      );
      return data?.id ? String(data.id) : null;
    } catch (error) {
      this.logger.warn(
        `WooCommerce webhook registration for ${topic} failed (${(error as AxiosError)?.response?.status ?? 'no status'})`,
      );
      return null;
    }
  }

  /** Best-effort cleanup on disconnect. */
  async deleteWebhook(
    storeUrl: string,
    credentials: WooCommerceCredentials,
    webhookId: string,
  ): Promise<void> {
    const normalized = normalizeStoreUrl(storeUrl);
    try {
      await axios.delete(
        `${normalized}/wp-json/wc/v3/webhooks/${webhookId}`,
        {
          auth: {
            username: credentials.consumerKey,
            password: credentials.consumerSecret,
          },
          params: { force: true },
          timeout: 15_000,
        },
      );
    } catch {
      this.logger.warn(`Could not delete WooCommerce webhook ${webhookId}`);
    }
  }
}
