import {
  Body,
  Controller,
  Get,
  Headers,
  HttpCode,
  HttpStatus,
  Logger,
  Post,
  Query,
  Req,
  Res,
} from '@nestjs/common';
import { ApiExcludeController } from '@nestjs/swagger';
import { SkipThrottle } from '@nestjs/throttler';
import type { Response } from 'express';
import { IntegrationProvider } from '@prisma/client';
import { IntegrationOAuthService } from './integration-oauth.service';
import { IntegrationWebhooksService } from './integration-webhooks.service';

/**
 * Public endpoints the platforms themselves call. Deliberately NOT behind
 * JwtAuthGuard: the caller is Shopify/WooCommerce/Amazon, not a logged-in
 * browser session. The security boundary is instead:
 *
 *  - OAuth callbacks : single-use server-side state (+ HMAC for Shopify)
 *  - Webhooks        : provider signature over the RAW request body
 *
 * @SkipThrottle for the same reason the Razorpay webhook does: a provider
 * retry storm must not be rejected by our own rate limiter.
 */
@ApiExcludeController()
@Controller('integrations')
export class IntegrationCallbacksController {
  private readonly logger = new Logger(IntegrationCallbacksController.name);

  constructor(
    private readonly oauthService: IntegrationOAuthService,
    private readonly webhooksService: IntegrationWebhooksService,
  ) {}

  // ── OAuth callbacks ───────────────────────────────────────────────────────

  /**
   * Shopify redirects the seller's browser here after they approve the app.
   * Always ends in a redirect back to the seller app — an error page rendered
   * on the API domain would be a dead end.
   */
  @Get('shopify/callback')
  @SkipThrottle()
  async shopifyCallback(
    @Query() query: Record<string, string>,
    @Res() res: Response,
  ) {
    const redirectTo = await this.oauthService.handleShopifyCallback(query);
    return res.redirect(redirectTo);
  }

  /**
   * WooCommerce POSTs the generated API key pair here, server to server.
   * The seller's browser goes to `return_url` separately, so this response is
   * never rendered. WooCommerce only checks for a 200.
   */
  @Post('woocommerce/callback')
  @SkipThrottle()
  @HttpCode(HttpStatus.OK)
  async woocommerceCallback(
    @Body()
    body: {
      key_id?: number;
      user_id?: string;
      consumer_key?: string;
      consumer_secret?: string;
      key_permissions?: string;
    },
  ) {
    await this.oauthService.handleWooCommerceCallback(body);
    return { ok: true };
  }

  /**
   * Amazon redirects here with `spapi_oauth_code`, `selling_partner_id` and
   * our state.
   */
  @Get('amazon/callback')
  @SkipThrottle()
  async amazonCallback(
    @Query() query: Record<string, string>,
    @Res() res: Response,
  ) {
    const redirectTo = await this.oauthService.handleAmazonCallback(query);
    return res.redirect(redirectTo);
  }

  /**
   * Shopify sends the seller here when they start the install from Shopify's
   * side rather than from Yukizi. We cannot know which Yukizi seller that is,
   * so send them to the Integrations page to start the flow properly.
   */
  @Get('shopify/install')
  @SkipThrottle()
  async shopifyInstall(@Res() res: Response) {
    return res.redirect(
      this.oauthService.buildReturnUrl(
        IntegrationProvider.SHOPIFY,
        'error',
        'start_from_yukizi',
      ),
    );
  }

  // ── Webhooks ──────────────────────────────────────────────────────────────

  /**
   * Shopify webhook receiver.
   *
   * `req.rawBody` is populated globally in main.ts; the HMAC is computed over
   * those exact bytes, so a re-serialised body would never validate.
   *
   * Always answers 200 once the signature checks out. Shopify retries on any
   * non-2xx, and a retry cannot fix a payload we simply have no mapping for —
   * the event is recorded and the delivery acknowledged.
   */
  @Post('shopify/webhook')
  @SkipThrottle()
  @HttpCode(HttpStatus.OK)
  async shopifyWebhook(
    @Req() req: { rawBody?: Buffer },
    @Headers('x-shopify-hmac-sha256') hmac?: string,
    @Headers('x-shopify-shop-domain') shopDomain?: string,
    @Headers('x-shopify-topic') topic?: string,
    @Headers('x-shopify-webhook-id') webhookId?: string,
  ) {
    return this.webhooksService.handleShopifyWebhook({
      rawBody: req.rawBody,
      hmac,
      shopDomain,
      topic,
      webhookId,
    });
  }

  /**
   * WooCommerce webhook receiver. The signature secret is per-webhook and was
   * generated by us at registration time, so the store is identified from the
   * source header before the signature can be checked.
   */
  @Post('woocommerce/webhook')
  @SkipThrottle()
  @HttpCode(HttpStatus.OK)
  async woocommerceWebhook(
    @Req() req: { rawBody?: Buffer },
    @Headers('x-wc-webhook-signature') signature?: string,
    @Headers('x-wc-webhook-source') source?: string,
    @Headers('x-wc-webhook-topic') topic?: string,
    @Headers('x-wc-webhook-id') webhookId?: string,
    @Headers('x-wc-webhook-delivery-id') deliveryId?: string,
  ) {
    return this.webhooksService.handleWooCommerceWebhook({
      rawBody: req.rawBody,
      signature,
      source,
      topic,
      webhookId,
      deliveryId,
    });
  }
}
